/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedPropertiesRouteImport } from './routes/_authenticated.properties'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated.settings.index'
import { Route as AuthenticatedPropertiesIndexRouteImport } from './routes/_authenticated.properties.index'
import { Route as AuthenticatedContractsIndexRouteImport } from './routes/_authenticated.contracts.index'
import { Route as AuthenticatedSettingsTeamRouteImport } from './routes/_authenticated.settings.team'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated.settings.profile'
import { Route as AuthenticatedSettingsOrganizationRouteImport } from './routes/_authenticated.settings.organization'
import { Route as AuthenticatedRentImportRouteImport } from './routes/_authenticated.rent.import'
import { Route as AuthenticatedPropertiesNewRouteImport } from './routes/_authenticated.properties.new'
import { Route as AuthenticatedPropertiesIdIndexRouteImport } from './routes/_authenticated.properties.$id.index'
import { Route as AuthenticatedPropertiesIdEditRouteImport } from './routes/_authenticated.properties.$id.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPropertiesRoute = AuthenticatedPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedPropertiesIndexRoute =
  AuthenticatedPropertiesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPropertiesRoute,
  } as any)
const AuthenticatedContractsIndexRoute =
  AuthenticatedContractsIndexRouteImport.update({
    id: '/contracts/',
    path: '/contracts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsTeamRoute =
  AuthenticatedSettingsTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsOrganizationRoute =
  AuthenticatedSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedRentImportRoute = AuthenticatedRentImportRouteImport.update({
  id: '/rent/import',
  path: '/rent/import',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPropertiesNewRoute =
  AuthenticatedPropertiesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedPropertiesRoute,
  } as any)
const AuthenticatedPropertiesIdIndexRoute =
  AuthenticatedPropertiesIdIndexRouteImport.update({
    id: '/$id/',
    path: '/$id/',
    getParentRoute: () => AuthenticatedPropertiesRoute,
  } as any)
const AuthenticatedPropertiesIdEditRoute =
  AuthenticatedPropertiesIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedPropertiesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/properties': typeof AuthenticatedPropertiesRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/rent/import': typeof AuthenticatedRentImportRoute
  '/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/contracts/': typeof AuthenticatedContractsIndexRoute
  '/properties/': typeof AuthenticatedPropertiesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/properties/$id/edit': typeof AuthenticatedPropertiesIdEditRoute
  '/properties/$id/': typeof AuthenticatedPropertiesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/rent/import': typeof AuthenticatedRentImportRoute
  '/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/contracts': typeof AuthenticatedContractsIndexRoute
  '/properties': typeof AuthenticatedPropertiesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/properties/$id/edit': typeof AuthenticatedPropertiesIdEditRoute
  '/properties/$id': typeof AuthenticatedPropertiesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/properties': typeof AuthenticatedPropertiesRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/_authenticated/rent/import': typeof AuthenticatedRentImportRoute
  '/_authenticated/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/_authenticated/contracts/': typeof AuthenticatedContractsIndexRoute
  '/_authenticated/properties/': typeof AuthenticatedPropertiesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/properties/$id/edit': typeof AuthenticatedPropertiesIdEditRoute
  '/_authenticated/properties/$id/': typeof AuthenticatedPropertiesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/properties'
    | '/settings'
    | '/properties/new'
    | '/rent/import'
    | '/settings/organization'
    | '/settings/profile'
    | '/settings/team'
    | '/contracts/'
    | '/properties/'
    | '/settings/'
    | '/properties/$id/edit'
    | '/properties/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/properties/new'
    | '/rent/import'
    | '/settings/organization'
    | '/settings/profile'
    | '/settings/team'
    | '/contracts'
    | '/properties'
    | '/settings'
    | '/properties/$id/edit'
    | '/properties/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/properties'
    | '/_authenticated/settings'
    | '/_authenticated/properties/new'
    | '/_authenticated/rent/import'
    | '/_authenticated/settings/organization'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/team'
    | '/_authenticated/contracts/'
    | '/_authenticated/properties/'
    | '/_authenticated/settings/'
    | '/_authenticated/properties/$id/edit'
    | '/_authenticated/properties/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/properties': {
      id: '/_authenticated/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AuthenticatedPropertiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/properties/': {
      id: '/_authenticated/properties/'
      path: '/'
      fullPath: '/properties/'
      preLoaderRoute: typeof AuthenticatedPropertiesIndexRouteImport
      parentRoute: typeof AuthenticatedPropertiesRoute
    }
    '/_authenticated/contracts/': {
      id: '/_authenticated/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof AuthenticatedContractsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/team': {
      id: '/_authenticated/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AuthenticatedSettingsTeamRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/organization': {
      id: '/_authenticated/settings/organization'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AuthenticatedSettingsOrganizationRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/rent/import': {
      id: '/_authenticated/rent/import'
      path: '/rent/import'
      fullPath: '/rent/import'
      preLoaderRoute: typeof AuthenticatedRentImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/properties/new': {
      id: '/_authenticated/properties/new'
      path: '/new'
      fullPath: '/properties/new'
      preLoaderRoute: typeof AuthenticatedPropertiesNewRouteImport
      parentRoute: typeof AuthenticatedPropertiesRoute
    }
    '/_authenticated/properties/$id/': {
      id: '/_authenticated/properties/$id/'
      path: '/$id'
      fullPath: '/properties/$id/'
      preLoaderRoute: typeof AuthenticatedPropertiesIdIndexRouteImport
      parentRoute: typeof AuthenticatedPropertiesRoute
    }
    '/_authenticated/properties/$id/edit': {
      id: '/_authenticated/properties/$id/edit'
      path: '/$id/edit'
      fullPath: '/properties/$id/edit'
      preLoaderRoute: typeof AuthenticatedPropertiesIdEditRouteImport
      parentRoute: typeof AuthenticatedPropertiesRoute
    }
  }
}

interface AuthenticatedPropertiesRouteChildren {
  AuthenticatedPropertiesNewRoute: typeof AuthenticatedPropertiesNewRoute
  AuthenticatedPropertiesIndexRoute: typeof AuthenticatedPropertiesIndexRoute
  AuthenticatedPropertiesIdEditRoute: typeof AuthenticatedPropertiesIdEditRoute
  AuthenticatedPropertiesIdIndexRoute: typeof AuthenticatedPropertiesIdIndexRoute
}

const AuthenticatedPropertiesRouteChildren: AuthenticatedPropertiesRouteChildren =
  {
    AuthenticatedPropertiesNewRoute: AuthenticatedPropertiesNewRoute,
    AuthenticatedPropertiesIndexRoute: AuthenticatedPropertiesIndexRoute,
    AuthenticatedPropertiesIdEditRoute: AuthenticatedPropertiesIdEditRoute,
    AuthenticatedPropertiesIdIndexRoute: AuthenticatedPropertiesIdIndexRoute,
  }

const AuthenticatedPropertiesRouteWithChildren =
  AuthenticatedPropertiesRoute._addFileChildren(
    AuthenticatedPropertiesRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsOrganizationRoute: typeof AuthenticatedSettingsOrganizationRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsTeamRoute: typeof AuthenticatedSettingsTeamRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsOrganizationRoute:
    AuthenticatedSettingsOrganizationRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsTeamRoute: AuthenticatedSettingsTeamRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPropertiesRoute: typeof AuthenticatedPropertiesRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedRentImportRoute: typeof AuthenticatedRentImportRoute
  AuthenticatedContractsIndexRoute: typeof AuthenticatedContractsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPropertiesRoute: AuthenticatedPropertiesRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedRentImportRoute: AuthenticatedRentImportRoute,
  AuthenticatedContractsIndexRoute: AuthenticatedContractsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
